@startuml

title __ACTIVATIONFUNCTIONS's Class Diagram__\n

  namespace neuralNetwork {
    namespace activationFunctions {
      interface neuralNetwork.activationFunctions.ActivationFunction {
          {static} + serialversionUID : long
          {abstract} + activationFunction()
          {abstract} + findDelta()
          {abstract} + getColour()
      }
    }
  }
  namespace neuralNetwork {
    namespace activationFunctions {
      class neuralNetwork.activationFunctions.Identity {
          + activationFunction()
          + findDelta()
          + getColour()
      }
    }
  }
  namespace neuralNetwork {
    namespace activationFunctions {
      class neuralNetwork.activationFunctions.Linear {
          + activationFunction()
          + findDelta()
          + getColour()
      }
    }
  }
  namespace neuralNetwork {
    namespace activationFunctions {
      class neuralNetwork.activationFunctions.ReLU {
          + activationFunction()
          + findDelta()
          + getColour()
      }
    }
  }
  namespace neuralNetwork {
    namespace activationFunctions {
      class neuralNetwork.activationFunctions.Sigmoid {
          + activationFunction()
          + findDelta()
          + getColour()
      }
    }
  }
  neuralNetwork.activationFunctions.Identity .up.|> neuralNetwork.activationFunctions.ActivationFunction
  neuralNetwork.activationFunctions.Linear .up.|> neuralNetwork.activationFunctions.ActivationFunction
  neuralNetwork.activationFunctions.ReLU .up.|> neuralNetwork.activationFunctions.ActivationFunction
  neuralNetwork.activationFunctions.Sigmoid .up.|> neuralNetwork.activationFunctions.ActivationFunction


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
